version: 2

shared: &shared
    steps:
        - checkout
        - restore_cache:
            keys:
                - '{{ .Environment.VENDOR_CACHE_KEY }}'
        - run:
            name: Install dependencies
            command: composer up $COMPOSER_OPTIONS
        - save_cache:
            paths:
                - vendor/
            key: '{{ .Environment.VENDOR_CACHE_KEY }}'
        - run:
            name: Lint PHP files
            command: find src tests -name "*.php" | xargs -n 1 php -l
        - run:
            name: Run tests
            command: php vendor/bin/phpunit --coverage-html=./build/coverage --log-junit=./build/tests-results/phpunit.xml
        - store_test_results:
            path: ./build/tests-results
        - store_artifacts:
            path: ./build/coverage
            destination: coverage

jobs:
    'php-5.6':
        <<: *shared
        environment:
            COMPOSER_OPTIONS: '--no-interaction --no-suggest --prefer-dist --prefer-stable'
            VENDOR_CACHE_KEY: 'v1-php-5.6-vendor-'
        docker:
            - image: 'circleci/php:5.6-cli-node-browsers-legacy'
    'php-5.6-lowest-deps':
        <<: *shared
        environment:
            COMPOSER_OPTIONS: '--no-interaction --no-suggest --prefer-dist --prefer-stable --prefer-lowest'
            VENDOR_CACHE_KEY: 'v1-php-5.6-lowest-vendor-'
        docker:
            - image: 'circleci/php:5.6-cli-node-browsers-legacy'
    'php-7.0':
        <<: *shared
        environment:
            COMPOSER_OPTIONS: '--no-interaction --no-suggest --prefer-dist --prefer-stable'
            VENDOR_CACHE_KEY: 'v1-php-7.0-vendor-'
        docker:
            - image: 'circleci/php:7.0-zts-stretch-node-browsers-legacy'
    'php-7.0-lowest-deps':
        <<: *shared
        environment:
            COMPOSER_OPTIONS: '--no-interaction --no-suggest --prefer-dist --prefer-stable --prefer-lowest'
            VENDOR_CACHE_KEY: 'v1-php-7.0-lowest-vendor-'
        docker:
            - image: 'circleci/php:7.0-zts-stretch-node-browsers-legacy'
    'php-7.1':
        <<: *shared
        environment:
            COMPOSER_OPTIONS: '--no-interaction --no-suggest --prefer-dist --prefer-stable'
            VENDOR_CACHE_KEY: 'v1-php-7.1-vendor-'
        docker:
            - image: 'circleci/php:7.1-cli-node-browsers-legacy'
    'php-7.1-lowest-deps':
        <<: *shared
        environment:
            COMPOSER_OPTIONS: '--no-interaction --no-suggest --prefer-dist --prefer-stable --prefer-lowest'
            VENDOR_CACHE_KEY: 'v1-php-7.1-lowest-vendor-'
        docker:
            - image: 'circleci/php:7.1-cli-node-browsers-legacy'
    'php-7.2':
        <<: *shared
        environment:
            COMPOSER_OPTIONS: '--no-interaction --no-suggest --prefer-dist --prefer-stable'
            VENDOR_CACHE_KEY: 'v1-php-7.2-vendor-'
        docker:
            - image: 'circleci/php:7.2-cli-node-browsers-legacy'
    'php-7.2-lowest-deps':
        <<: *shared
        environment:
            COMPOSER_OPTIONS: '--no-interaction --no-suggest --prefer-dist --prefer-stable --prefer-lowest'
            VENDOR_CACHE_KEY: 'v1-php-7.2-lowest-vendor-'
        docker:
            - image: 'circleci/php:7.2-cli-node-browsers-legacy'

workflows:
    version: 2
    build:
        jobs:
            - 'php-5.6'
            - 'php-5.6-lowest-deps'
            - 'php-7.0'
            - 'php-7.0-lowest-deps'
            - 'php-7.1'
            - 'php-7.1-lowest-deps'
            - 'php-7.2'
            - 'php-7.2-lowest-deps'
